--- 
pid: tmp/pids/thin.pid
log: log/thin.log
timeout: 30
max_conns: 1024
port: 5000
chdir: /home/webmaster/avidmanager.com/current
environment: production
max_persistent_conns: 512
daemonize: true
address: 0.0.0.0
servers: 4
